#!/usr/bin/env bash
# This script displays information about subdomains of a given domain.

check_subdomain() 
{
    local domain="$1"
    local subdomain="$2"
    
    dig_output=$(dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:')
    record_type=$(echo "$dig_output" | awk '/IN\s/{print $4}')
    destination=$(echo "$dig_output" | awk '/IN\s/{print $5}')

    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

main() 
{
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        check_subdomain "$domain" "$sub"
    done
}

main "$@"

