#!/usr/bin/env bash

# Check if Nginx is not running
if service nginx status | grep -q "nginx is not running"; then
    # Update Nginx configuration
    sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
    
    # Restart Nginx service
    service nginx restart
fi
