#!/usr/bin/env bash
# Stops 4-to_infinity_and_beyond process

# Find the PID of the process
pid=$(pgrep -f "bash ./4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
    # Use pkill to stop the process
    pkill -P "$pid"
    echo "Process stopped successfully"
else
    echo "Process is not running"
fi
